### ISSUE TITLE
Recursive calls to `process_data` in `hdf5_hl_base` might not handle all datatype conditions?

### ISSUE THREAD

**Issue by alexpreynolds** [usnistgov/h5wasm#7]
I used `h5dump` to interrogate my container, which contains a compound of three 32-bit floats and a 32-bit unsigned integer:

```
HDF5 "/Users/areynolds/Desktop/data.h5" {
GROUP "/" {
   GROUP "data" {
      DATASET "tsg8n0ki" {
         DATATYPE  H5T_COMPOUND {
            H5T_ARRAY { [3] H5T_IEEE_F32LE } "xyz";
            H5T_STD_U32LE "label_idx";
         }
         DATASPACE  SIMPLE { ( 100 ) / ( 100 ) }
         DATA {
         (0): {
               [ 6.31591, 3.62053, 5.03742 ],
               0
            },
         (1): {
               [ 4.09167, 4.58137, 5.51809 ],
               1
            },
            ...
```

Calling `slice` on a row of compound data calls `process_data`, which in turn returns an array of twelve `Uint8`s, along with the unsigned integer.

I can convert the twelve-byte portion of the per-row slice to three floats with the following function:

```
  public sliceRawUint8XyzToXyz = (rawXyz: number[], littleEndian : boolean) : number[] => {
    const results = [];  
    const bytes = 4;
    const points = 3;
    const buffer = new ArrayBuffer(bytes);
    const view = new DataView(buffer);

    if (littleEndian) {
      for (let i = 0; i < points; i++) {
        rawXyz.slice(i * bytes, (i + 1) * bytes).reduceRight(function (_, b, i) : any { view.setUint8(Math.abs(i - bytes + 1), b) }, rawXyz[points]);
        const acc = parseFloat(view.getFloat32(0).toFixed(6));
        results.push(acc);
      }
    }
    else {
      for (let i = 0; i < points; i++) {
        rawXyz.slice(i * bytes, (i + 1) * bytes).reduceRight(function (_, b, i) : any { view.setUint8(i, b) }, rawXyz[0]);
        const acc = parseFloat(view.getFloat32(0).toFixed(6));
        results.push(acc);
      }
    }

    return results;
  }
```

This gives me back the original array of three floats in the HDF5 table row.

I'm filing an issue in case it might be worth handling the `H5T_ARRAY` or other types in the `process_data` conditions, when constructing results. However, I admit I don't know how much work or how worthwhile it would be, if compound types are rare or discouraged.

**Comment by bmaranville** [comment]
Ah yes - I have not done anything to support the Array type, which I had never encountered "in the wild".  In this case it's even nested inside a Compound type!  Definitely not something I've seen before.  

Would you say it's something you really need (e.g. some other library tends to have these in its default output),  or just a 'nice-to-have' to fill out the coverage of possible hdf5 files?

**Comment by bmaranville** [comment]
It looks like H5T_ARRAY will be pretty straightforward to support - [the full list of datatype classes](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5T.html#Datatype-GetClass) is:

- H5T_INTEGER
- H5T_FLOAT
- H5T_STRING
- H5T_BITFIELD
- H5T_OPAQUE
- H5T_COMPOUND
- H5T_REFERENCE
- H5T_ENUM
- H5T_VLEN
- H5T_ARRAY

There is already support for INTEGER, FLOAT, STRING (and VLEN && STRING), COMPOUND and soon ARRAY.  Of the remaining classes: OPAQUE is what it says it is (nothing to do there in processing), REFERENCE is pointers to objects or regions within the same file, ENUM is a special case of INTEGER and BITFIELD I don't know much about (h5py reads them as unsigned integers and leaves it up to the user to interpret them)

**Comment by bmaranville** [comment]
This has been addressed in v0.2.0, just released.  Give it a try!

**Comment by alexpreynolds** [comment]
it appears to work in that I get back an array containing the three floats — looks pretty good!

I did run into Typescript errors after upgrading from v0.1.8 to v0.2.0.

Here is an example of one error I get:

```
ERROR in src/App.tsx:186:32
TS2339: Property 'get' does not exist on type 'Group | Dataset'.
  Property 'get' does not exist on type 'Dataset'.
    184 |         console.log(`data.attrs ${JSON.stringify(data.attrs)}`);
    185 |         // console.log(`data.keys ${JSON.stringify(data.keys())}`);
  > 186 |         const dataGroup = data.get('tsg8n0ki');
        |                                ^^^
    187 |         const dataSlice : any[] = dataGroup.slice([[0, 2]]);
    188 |         console.log(`dataSlice ${JSON.stringify(dataSlice)}`);
```

Changing the type of `data` "fixes" the error, i.e., changing from:

```
const data = f.get('data');
```

To:

```
const data = f.get('data') as hdf5.Group;
```

But the error message is confusing, because `data` is a `Group` and not a `Dataset`. 

Using `h5dump` to interrogate [my test container](https://somebits.io/data.h5) shows this is a `Group`:

```
HDF5 "/Users/areynolds/Desktop/data.h5" {
GROUP "/" {
   GROUP "data" {
      DATASET "tsg8n0ki" {
         DATATYPE  H5T_COMPOUND {
            H5T_ARRAY { [3] H5T_IEEE_F32LE } "xyz";
            H5T_STD_U32LE "label_idx";
         }
         ...
```

I found retrieving other values from the container also required casting using `as hdf5.*`.

**Comment by bmaranville** [comment]
I think the error is because you don't know at compile-time whether a ```get``` operation will return a Group or a Dataset, and typescript is applying the most restrictive typing from the union:  Group | Dataset (i.e., the only safe assumption is that it doesn't have a ```get``` method since it might be a Dataset).  There could be separate methods get_group and get_dataset, but that's sort of the same as casting them if you already know what they are going to be.  You can also apply guard logic as below, but from your code it looks like casting ``` as hdf5.Group``` is the most logical thing if you are getting a member and you know it's a group.
```js
if (data instanceof hdf5.Group) {
  let dataGroup = data.get('tsg8n0ki');
  // ...  
```

The ambiguity about what you'll get back when you retrieve an object by name is deep in the HDF5 C API - which is why there's a method H5Oget_info_by_name that you can call to get the type, and it's called when you use e.g. 
```js
data.get_type('tsg8n0ki'); // returns 1 , which == Module.H5O_TYPE_DATASET
```

**Comment by alexpreynolds** [comment]
Thanks very much for patiently explaining this and for adding features! This is very useful.
